development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: your_application_development

test:
  adapter: redis
  url:  "redis://localhost:6379/1" 
  channel_prefix: zaobridge_test
